-- 创建 bsst_recharge_card 表
CREATE TABLE `ea8_bsst_recharge_card` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `card_no` varchar(32) NOT NULL COMMENT '充值卡号',
  `card_type` tinyint(1) DEFAULT '1' COMMENT '卡类型(1:普通卡,2:VIP卡,3:活动卡)',
  `amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '充值金额',
  `original_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '原始金额',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态(1:未使用,2:已使用,3:已过期,4:已作废)',
  `batch_no` varchar(50) DEFAULT NULL COMMENT '批次号',
  `expire_time` int(11) DEFAULT '0' COMMENT '过期时间',
  `soft_name` varchar(50) NOT NULL COMMENT '软件名称',
  `creator_id` int(11) DEFAULT NULL COMMENT '创建者ID',
  `used_user_id` int(11) DEFAULT NULL COMMENT '使用用户ID',
  `used_time` int(11) DEFAULT NULL COMMENT '使用时间',
  `used_ip` varchar(45) DEFAULT NULL COMMENT '使用IP',
  `used_device` varchar(255) DEFAULT NULL COMMENT '使用设备信息',
  `sort` int(11) DEFAULT '0' COMMENT '排序',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_time` int(11) DEFAULT NULL COMMENT '创建时间',
  `update_time` int(11) DEFAULT NULL COMMENT '更新时间',
  `delete_time` int(11) DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_card_no` (`card_no`),
  KEY `idx_status` (`status`),
  KEY `idx_soft_name` (`soft_name`),
  KEY `idx_batch_no` (`batch_no`),
  KEY `idx_expire_time` (`expire_time`),
  KEY `idx_used_user_id` (`used_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='充值卡表'; 